Drink.create(name: "IPA-400", price: 6.00)
Drink.create(name: "Traveler", price: 3.50)
Drink.create(name: "Red Ale", price: 2.00)
Drink.create(name: "Abu", price: 8.25)
Drink.create(name: "Budlight", price: 2.00)
Customer.create(username: "Ryne", email: "ryne.stajcar@gmail.com", password: "aass")